Plantae.Web/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plantae.Web.Models;
using Plantae.Core.Repositories;
using Plantae.Core;

namespace Plantae.Web.Controllers
{
    public class ContaController : Controller
    {
        ContaRepository contaRepository;

        public ContaController()
        {
            contaRepository = new ContaRepository(new ContextFactory());
        }

        //
        // GET: /Conta/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Conta/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Conta/Create

        public ActionResult Create()
        {
            return ContextDependentView();
        } 

        //
        // POST: /Conta/Create

        [HttpPost]
        public ActionResult Create(ContaModel model)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult JsonCreate(ContaModel model)
        {
            if (ModelState.IsValid)
            {
                CONTA conta = new CONTA(model, User.Identity.Name);

                contaRepository.InsertOnSubmit(conta);
                contaRepository.Save();

                return Json(new { success = true });
            }

            return Json(new { errors = GetErrorsFromModelState() });
        }
        
        //
        // GET: /Conta/Edit/5
 
        public ActionResult Edit(long id)
        {
            var conta = contaRepository.FindById(id, User.Identity.Name);

            return ContextDependentView(new ContaModel(conta));
        }

        //
        // POST: /Conta/Edit/5

        [HttpPost]
        public ActionResult Edit(long id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult JsonEdit(long id, ContaModel model)
        {
            if (ModelState.IsValid)
            {
                CONTA conta = contaRepository.FindById(id, User.Identity.Name);

                conta.Update(model.Nome, model.DataInicial, model.SaldoInicial);

                contaRepository.Save();

                return Json(new { success = true });
            }

            return Json(new { errors = GetErrorsFromModelState() });
        }

        //
        // GET: /Conta/Delete/5
 
        public ActionResult Delete(long id)
        {
            return ContextDependentView();
        }

        //
        // POST: /Conta/Delete/5

        [HttpPost]
        public ActionResult Delete(long id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private ActionResult ContextDependentView(ContaModel model = null)
        {
            string actionName = ControllerContext.RouteData.GetRequiredString("action");
            if (Request.QueryString["content"] != null)
            {
                ViewBag.FormAction = "Json" + actionName;
                return PartialView(model);
            }
            else
            {
                ViewBag.FormAction = actionName;
                return View(model);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        private IEnumerable<string> GetErrorsFromModelState()
        {
            return ModelState.SelectMany(x => x.Value.Errors
                .Select(error => error.ErrorMessage));
        }
    }
}

Plantae.Web/Controllers/TransacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plantae.Core;
using Plantae.Core.Repositories;
using Plantae.Web.Models;
using Plantae.Core.Services;
using Plantae.Web.Services;

namespace Plantae.Web.Controllers
{
    [Authorize(Roles="Membros")]
    public class TransacoesController : Controller
    {
        ContaRepository contaRepository;
        CategoriaRepository categoriaRepository;
        JournalRepository journalRepository;
        TransacaoRepository transacaoRepository;
        ExtratoServices extratoServices;

        public TransacoesController()
        {
            contaRepository = new ContaRepository(new ContextFactory());
            categoriaRepository = new CategoriaRepository(new ContextFactory());
            journalRepository = new JournalRepository(new ContextFactory());
            transacaoRepository = new TransacaoRepository(new ContextFactory());
            extratoServices = new ExtratoServices();
        }

        //
        // GET: /Transacoes/

        public ActionResult Index()
        {
            // Recupera os dados de conta e período do extrato
            CONTA selectedConta = null;
            DateTime startDate = DateTime.Now.AddMonths(-1);
            DateTime endDate = DateTime.Now;

            // Cria o bag de contas
            ViewBag.Contas = contaRepository.GetAll(User.Identity.Name);

            // Cria o bag de extratos
            if(selectedConta != null)
                ViewBag.Extrato = extratoServices.BuildExtratoCollection(transacaoRepository.GetByContaAndDate(selectedConta, startDate, endDate, User.Identity.Name), selectedConta.GetSaldoEm(startDate));
            else
                ViewBag.Extrato = extratoServices.BuildExtratoCollection(transacaoRepository.GetAll(User.Identity.Name), transacaoRepository.GetTotalTransacoesEm(startDate, User.Identity.Name));


            return View();
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            return View();
        }
        
        /// <summary>
        /// Ação para criar uma transação. Obtém o tipo da transação pela rota recebida na requisição
        /// e chama a View com o form para criar a nova transação.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            string tipo = Request.QueryString["tipo"];

            ViewBag.TipoTransacao = GetTipoTransacaoValue(tipo).ToString();
            ViewBag.ContasDebito = new SelectList(contaRepository.GetAll(User.Identity.Name), "ContaID", "Nome");
            ViewBag.ContasCredito = new SelectList(contaRepository.GetAll(User.Identity.Name), "ContaID", "Nome");
            ViewBag.Categorias = new SelectList(categoriaRepository.GetAll(User.Identity.Name), "CategoriaID", "Nome");

            return ContextDependentView();
        } 

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(JournalModel model)
        {
            try
            {
                throw new NotImplementedException();

                //return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult JsonCreate(JournalModel model)
        {
            UpdateJournalModelProperties(model, ModelState);

            if (ModelState.IsValid)
            {
                JOURNAL journal = new JOURNAL(model, User.Identity.Name);

                journalRepository.InsertOnSubmit(journal);
                journalRepository.Save();

                return Json(new { success = true });
            }

            return Json(new { errors = GetErrorsFromModelState() });
        }
        
        //
        // GET: /Transacoes/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Transacoes/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Transacoes/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Transacoes/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void UpdateJournalModelProperties(JournalModel model, ModelStateDictionary modelState)
        {
            if (model.CategoriaID != 0)
                ModelState.Remove("Categoria");
            else
                ModelState.Remove("CategoriaID");

            if (model.ContaCreditoID.HasValue)
                model.CONTACREDITO = contaRepository.FindById(model.ContaCreditoID.Value, User.Identity.Name);
            
            if (model.ContaDebitoID.HasValue)
                model.CONTADEBITO = contaRepository.FindById(model.ContaDebitoID.Value, User.Identity.Name);
            
            model.CATEGORIA = categoriaRepository.FindById(model.CategoriaID, User.Identity.Name);
        }

        private int GetTipoTransacaoValue(string tipo)
        {
            switch (tipo)
            {
                case "credito":
                    return (int)PLANTAEUTILS.TipoTransacao.Credito;
                case "debito":
                    return (int)PLANTAEUTILS.TipoTransacao.Debito;
                case "transferencia":
                    return (int)PLANTAEUTILS.TipoTransacao.Transferencia;
                default:
                    return (int)PLANTAEUTILS.TipoTransacao.Credito;

            }
        }

        private ActionResult ContextDependentView(ContaModel model = null)
        {
            string actionName = ControllerContext.RouteData.GetRequiredString("action");
            if (Request.QueryString["content"] != null)
            {
                ViewBag.FormAction = "Json" + actionName;
                return PartialView(model);
            }
            else
            {
                ViewBag.FormAction = actionName;
                return View(model);
            }
        }

        private IEnumerable<string> GetErrorsFromModelState()
        {
            return ModelState.SelectMany(x => x.Value.Errors
                .Select(error => error.ErrorMessage));
        }
    }
}

Plantae.Web/Views/Shared/_ContasResumoPartial.cshtml
<table class="plantae-table plantae-contas-table">
<thead>
    <tr>
        <th>
            <span class="float-left">Contas</span>
            <span class="float-right"><img src="../../Images/icons/add.png" class="icon" />@Html.ActionLink("nova conta", "Create", "Conta", routeValues: null, htmlAttributes: new { @class = "ajax-link", id = "novaContaLink", data_dialog_title = "nova conta" })</span>
            
        </th>
    </tr>
</thead>
<tbody>
@foreach (Plantae.Core.CONTA conta in ViewBag.Contas)
{
    <tr>
        <td>
            <div>
                <span>@Html.ActionLink(conta.Nome, "Edit", "Conta", routeValues: new { id = conta.ContaID }, htmlAttributes: new { @class = "ajax-link", id = "editarContaLink", data_dialog_title = "editar conta" })</span>
            </div>    
            <div>
                <span class="contas-saldo saldo-positivo">@conta.SaldoAtual</span>
            </div>
        </td>
    </tr>
}
</tbody>
</table>

Plantae.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="@Url.Content("~/Content/plantae-styles.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/plantae-components.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/2011.3.1129/kendo.metro.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/custom-theme/jquery-ui.custom.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.meio.mask.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/plantae-scripts.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/globalize.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/cultures/globalize.culture.pt-BR.js")" type="text/javascript"></script>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><img src="../../Images/logo.png" alt="pratinhas finanças" /></p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LogOnPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("início", "Index", "Home")</li>
                            <li>@Html.ActionLink("transações", "Index", "Transacoes")</li>
                            <li>@Html.ActionLink("orçamentos", "Index", "Orcamentos")</li>
                            <li>@Html.ActionLink("análises", "Index", "Analises")</li>
                            <li>@Html.ActionLink("sobre", "About", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Pratinhas finanças</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

Plantae.Web/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <p>
        Hello, @Html.ActionLink(User.Identity.Name, "ChangePassword", "Account", null, new { @class = "username" })!
        @Html.ActionLink("Log Off", "LogOff", "Account")
    </p>
} else {
    <ul>
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { @class = "ajax-link", id = "registerLink", data_dialog_title = "Registration" })</li>
        <li>@Html.ActionLink("Log on", "LogOn", "Account", routeValues: null, htmlAttributes: new { @class = "ajax-link", id = "logonLink", data_dialog_title = "Identification" })</li>
    </ul>
}

Plantae.Web/Views/Shared/_TransacoesExtratoPartial.cshtml
<table class="plantae-table plantae-extrato-table">
<thead>
    <tr>
        <th colspan="5">
            <span class="float-left">Transações</span>
            <span class="float-right">
                @Html.ActionLink("+ novo crédito", "Create", "Transacoes", routeValues: new { tipo = "credito" }, htmlAttributes: new { @class = "ajax-link", id = "novaTransacaoLink", data_dialog_title = "novo crédito" })
                @Html.ActionLink("- novo débito", "Create", "Transacoes", routeValues: new { tipo = "debito" }, htmlAttributes: new { @class = "ajax-link", id = "novaTransacaoLink", data_dialog_title = "novo débito" })
                @Html.ActionLink("<> nova transferência ", "Create", "Transacoes", routeValues: new { tipo = "transferencia" }, htmlAttributes: new { @class = "ajax-link", id = "novaTransacaoLink", data_dialog_title = "nova transferência" })
            </span>
        </th>
    </tr>
</thead>
<tbody>
@foreach (Plantae.Web.Models.ExtratoModel transacao in ViewBag.Extrato)
{
    <tr>
        <td>@transacao.Conta</td>
        <td>@transacao.Data</td>
        <td>@transacao.Categoria</td>
        <td>@transacao.Valor</td>
        <td>@transacao.Saldo</td>
    </tr>
}
</tbody>
</table>